### ISSUE TITLE
Receives "internal error" when attempting to add data

### ISSUE THREAD

**Issue by ingridgarfeltpaulsen** [COATnor/COAT_portal_issues#152]
I want to add a new protocol in the official coat data portal, but when I push the button «add data» I receive the error message: "Server Error, an internal server error occurred". Please help!

**Comment by frafra** [comment]
Hi,
this is a regression (the catalogue is not able to contact DataCite servers for the DOI); we alerted our IT department, and it should be fixed soon, hopefully.

**Comment by frafra** [comment]
It should have been fixed. Could you please check it?

**Comment by ingridgarfeltpaulsen** [comment]
Yup!

**Comment by ingridgarfeltpaulsen** [comment]
It is not fixed yet, I still receive the internal error message when I push
add data. I use Chrome if it makes any difference.

Ingrid

**Comment by frafra** [comment]
Thank you for your feedback, I can see the problem. We are working on that.

**Comment by frafra** [comment]
Could you check again, please?

**Comment by ingridgarfeltpaulsen** [comment]
Thank you, it works :)
