### ISSUE TITLE
error when deleting resource

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#166]
I can not delete a demaged datafile of a private dataset on coatdemo. I get an 'Internal server error'.

**Comment by frafra** [comment]
I just deployed a new version on coatdemo.coat.no. I am able to delete resources.

**Comment by hannaboe** [comment]
I still can't delete broken resources from existing datasets. For examples from 'v_heath_ground_cover_experimental_v2'. 
If I create a new dataset, deleting works fine

**Comment by frafra** [comment]
Can you produce a list of resources you need to delete?

**Comment by hannaboe** [comment]
I could, but it's a bit of work. I think it would be easier if I could delete and reupload the resources.
An example for a resource that should be deleted is [V_heath_ground_cover_experimental_2018.txt](https://coatdemo.coat.no/dataset/v_heath_ground_cover_experimental_v2/resource/9f12a575-b0ee-4d09-83b3-75550390f699).

**Comment by hannaboe** [comment]
Should I make a list with the datasets that have to be deleted?

**Comment by frafra** [comment]
That was a bug, actually. `scientific_name` and other parameters are not flagged as required, but the system internally assumed they were. Removing or adding a resource updates the metadata of the dataset, which failed due to some empty parameters. The software is able to handle that case properly.
